using OpenCvSharp.WpfExtensions; using System.ComponentModel; using System.Windows;
namespace EyeContactCam;
public partial class MainWindow:Window{
 private readonly CameraPipeline _pipeline=new();private readonly ObsVirtualCamera _obs=new();private readonly OutputWindow _output=new();private CancellationTokenSource? _cameraCts;private volatile bool _scanning;private DateTime _scanStarted;private int _scanSamples;
 public MainWindow(){InitializeComponent();ObsStatus.Text=_obs.IsInstalled?"OBS найден. При первом запуске добавьте захват окна «EyeContact Cam Output».":"OBS Studio не установлен — потребуется для Windows 10.";VirtualButton.Content=_obs.IsInstalled?"Активировать виртуальную камеру":"Установить OBS Studio";CorrectionCheck.IsEnabled=_pipeline.HasCalibration;if(!_pipeline.HasCalibration)StatusText.Text="Нужен новый скан: смотрите точно в объектив";}
 private void StartCamera_Click(object sender,RoutedEventArgs e){if(_cameraCts is not null){StopCamera();return;}_cameraCts=new();StartButton.Content="Остановить камеру";ScanButton.IsEnabled=true;EmptyText.Visibility=Visibility.Collapsed;StatusText.Text="Камера запущена";_=Task.Run(()=>CaptureLoop(_cameraCts.Token));}
 private void CaptureLoop(CancellationToken token){try{_pipeline.Open(0);while(!token.IsCancellationRequested){using var frame=_pipeline.Read();if(frame is null){Thread.Sleep(20);continue;}bool enabled=false;double strength=0;Dispatcher.Invoke(()=>{enabled=CorrectionCheck.IsChecked==true;strength=StrengthSlider.Value;});using var result=_pipeline.Process(frame,enabled,strength);if(_scanning&&_pipeline.LastEyesFound==2){_scanSamples++;var pct=Math.Min(100,(DateTime.UtcNow-_scanStarted).TotalSeconds/3*100);Dispatcher.Invoke(()=>ScanProgress.Value=pct);if(pct>=100&&_scanSamples>=20){_pipeline.SaveCalibration();_scanning=false;Dispatcher.Invoke(()=>{CorrectionCheck.IsEnabled=true;ScanButton.Content="Пересканировать";StatusText.Text="Скан завершён — профиль глаз сохранён";});}}var bitmap=result.ToWriteableBitmap();bitmap.Freeze();Dispatcher.Invoke(()=>{PreviewImage.Source=bitmap;_output.SetFrame(bitmap);TrackingText.Text=_pipeline.LastEyesFound==2?(enabled?$"Глаза найдены • сдвиг {_pipeline.LastCorrectionMagnitude:0.0} px":"Глаза найдены • эффект выключен"):$"Глаза найдены: {_pipeline.LastEyesFound}/2";});}}catch(Exception ex){Dispatcher.Invoke(()=>StatusText.Text="Ошибка камеры: "+ex.Message);}finally{_pipeline.Close();}}
 private void Scan_Click(object sender,RoutedEventArgs e){_pipeline.BeginCalibration();_scanSamples=0;_scanStarted=DateTime.UtcNow;_scanning=true;ScanProgress.Value=0;ScanButton.Content="Идёт сканирование…";StatusText.Text="Смотрите прямо в объектив и не двигайте головой";}
 private void VirtualCamera_Click(object sender,RoutedEventArgs e){if(!_obs.IsInstalled){_obs.OpenDownloadPage();return;}if(_cameraCts is null)StartCamera_Click(sender,e);_output.Show();_output.Activate();StatusText.Text=_obs.Start();MessageBox.Show("OBS запускается с виртуальной камерой.\n\nПри первом использовании в OBS добавьте источник «Захват окна» → [EyeContactCam] EyeContact Cam Output. Затем в Google Meet выберите «OBS Virtual Camera». Конфигурация OBS сохранится для следующих запусков.","Подключение к Google Meet",MessageBoxButton.OK,MessageBoxImage.Information);}
 private void StopCamera(){_cameraCts?.Cancel();_cameraCts?.Dispose();_cameraCts=null;StartButton.Content="Запустить камеру";ScanButton.IsEnabled=false;StatusText.Text="Камера остановлена";}
 private void Window_Closing(object? sender,CancelEventArgs e){StopCamera();_pipeline.Dispose();_output.AllowClose=true;_output.Close();}
}
